### ISSUE TITLE
_Cannot marshal <type 'wrapper_descriptor'> objects_

### ISSUE THREAD

**Issue by ptrourke** [maxcutler/python-wordpress-xmlrpc#100]
I'm getting this error when I try to send a WordPressPost object using the EditPost method. It looks as though python's xmlrpc is iterating through the `_def` attribute of the WordPressPost object to get to this. My post is a large one with a number of custom_fields (using the advanced custom fields plugin). I'm using various versions of python 2.7 (2.7.10 on OS X El Capitan, 2.7.6 on Ubuntu 14.04). Any ideas of what to look for? 

Thanks!

**Comment by n3storm** [comment]
How did you solve it?
