### ISSUE TITLE
Fault 500: A term with the name provided already exists with this parent

### ISSUE THREAD

**Issue by djiesamsoe** [maxcutler/python-wordpress-xmlrpc#104]
hello @maxcutler ,
I have problems when I create a new post with the categories that are already in use in the previous post, but there was an error as below:

> `Fault: <Fault 500: 'A term with the name provided already exists with this parent.'>`

The script that I use:

> post = WordPressPost()
>         post.post_type = 'post'
>         post.terms_names = { 'post_tag': categorys, 'category': categorys }
>         post.title = title
>         post.content = content
>         post.post_status = 'publish'
>         post.thumbnail = attachment_id
>         client.call(posts.NewPost(post))

i'm use VPS server.

Please help !

**Comment by ervaibhavsinghal** [comment]
i'm also facing this issue.. but in my case categories are different from first one.

**Comment by ervaibhavsinghal** [comment]
hi @djiesamsoe i've also faced this issue, with the help of this trick, error removed.
`import cgi`
`categorys = cgi.escape(categorys, True)`
`post.terms_names = { 'post_tag': categorys, 'category': categorys }`

try this, may your problem get resolved.

**Comment by djiesamsoe** [comment]
Thanks @ervaibhavsinghal ,
I will try to script that you provide.

**Comment by djiesamsoe** [comment]
thanks @ervaibhavsinghal .
Your script is work for me.
Thanks
