### ISSUE TITLE
_Underscored meta in custom field is not working

### ISSUE THREAD

**Issue by ervaibhavsinghal** [maxcutler/python-wordpress-xmlrpc#105]
Hello, 

when i'm using this code, new post upload successfully.
`
widget.custom_fields.append({
        'key': 'price',
        'value': 2
})
`

but when i put underscore in key value like this:
`
widget.custom_fields.append({
        'key': '_price',
        'value': 2
})
`

it's not working?? can one sort out this issue.

Thanks

**Comment by maxcutler** [comment]
This is a security measure in WordPress' XML-RPC API, custom fields that start with an underscore are considered private and not exposed through the API by default. What is creating this `_price` custom field? If it is code you wrote then you can use the `register_meta` function args to expose it to the API, or you can use the `is_protected_meta` filter to mark this field as not protected.

**Comment by ervaibhavsinghal** [comment]
thnks @maxcutler i'hv already use register_meta function to register the meta_key, when i checked it show "TRUE", according to WordPress codex, it's register.
but my code is not working.

**Comment by ervaibhavsinghal** [comment]
http://python-wordpress-xmlrpc.readthedocs.io/en/latest/ref/wordpress.html#WordPressOption
i'hv gone through this code,  date (datetime) is not work properly.
my code is this:
`from datetime import datetime`
`now = datetime.now()`
`post = WordPressPost()`
`post.date = datetime(now.year, now.month, now.day, now.hour, now.minute, now.second, now.microsecond)`

post publish time shows wrong time. can you please sort out this issue also.
