### ISSUE TITLE
Can't set categories or tags as in the example

### ISSUE THREAD

**Issue by benlong100** [maxcutler/python-wordpress-xmlrpc#121]
I've been playing with the demo code and while it's creating a post with no problem, it's not setting the category or tags. Here's what I've got to create a post:

wp=Client('http://500kelvin.doesntexist.com/xmlrpc.php','ben','cactus42')
post=WordPressPost()
post.title = 'Come As You Are'
post.content = "Blah blah blah"
post.terms_names = {'category':'music','post_tag':'testing testing'}
post.post_status = 'publish'
theNewPostID = wp.call(NewPost(post))

I do have a Music category defined, and I've tried using both 'Music' and 'music' in the call, but posts always come in uncategorized. What am I missing?

Thanks

**Comment by n3storm** [comment]
From the docs: **Note that terms_names is a dictionary with taxonomy names as keys and _list_ of strings as values.**
