### ISSUE TITLE
xmlrpclib.ProtocolError: <ProtocolError for blog.example.com/xmlrpc.php: 403 Forbidden>

### ISSUE THREAD

**Issue by jonathan-s** [maxcutler/python-wordpress-xmlrpc#69]
I stumbled upon this problem. According to this [post](http://stackoverflow.com/questions/25118760/setting-custom-headers-on-a-python-wordpress-xmlrpc-request) on stackoverflow it's due to the agent not being accepted. So I subclassed the `Transport` class into this: 

    class SpecialTransport(Transport):
        user_agent = ('Mozilla/5.0 (Windows NT 6.0) AppleWebKit/537.31 (KHTML, like Gecko) Chrome/26.0.1410.43 Safari/537.31')

However I now get the error described in issue #65, despite having https in the url. So I'm not sure what's happening really.

**Comment by maxcutler** [comment]
For HTTPS connections, you should use `SafeTransport` as your base class. Per the [documentation](https://docs.python.org/2/library/xmlrpclib.html#xmlrpclib.ServerProxy) for `xmlrpclib` this is what Python does by default.

**Comment by jonathan-s** [comment]
Ok, `SafeTransport` solved that problem. The 403 forbidden problem is still there though.

**Comment by jonathan-s** [comment]
Issue solved, apparently it was a password issue.
