### ISSUE TITLE
Leading and trailing whitespaces

### ISSUE THREAD

**Issue by Daiwen** [maxcutler/python-wordpress-xmlrpc#75]
when creating the Client class, I receive the following error:
xml.parsers.expat.ExpatError: XML or text declaration not at start of entity: line 2, column 0

This is due to the fact that I am receiving the xml data with a leading \n .

I saw that this issue had already been reported here:
https://github.com/maxcutler/python-wordpress-xmlrpc/issues/12

and a solution you developed would be to use this:
https://github.com/maxcutler/wordpress-xmlrpc-dewhitespacer

Unfortunately, I don't have access to the server, is there another solution for me to get rid of these whitespaces?

**Comment by maxcutler** [comment]
You could implement a `Transport` class that strips leading/trailing whitespace from the server response before it runs through the XML parser. Version 2.3 of this library added a `transport` argument to the `Client` constructor, see the docs: http://python-wordpress-xmlrpc.readthedocs.org/en/latest/ref/client.html#Client

I hope to one day ship such a `Transport` implementation with the library, but I have not had time to build one yet. If you undertake such work, I would be more than happy to merge a pull request.

**Comment by johnidm** [comment]
I found a solution for this problem here: http://stackoverflow.com/questions/15191551/xml-rpc-python-client-raising-xml-parsers-expat-expaterror-exception?answertab=active#tab-top
