### ISSUE TITLE
No module named compat

### ISSUE THREAD

**Issue by djiesamsoe** [maxcutler/python-wordpress-xmlrpc#94]
Please help !

i try in my server:

```
>>> from wordpress_xmlrpc.compat import xmlrpc_client
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named compat
>>>
```

my server using Centos
regards

**Comment by maxcutler** [comment]
Can you provide more context about how you are trying to use this library? I can't think of a situation in which you would need to import `xmlrpc_client` like you have in this example, normally you would interact with `wordpress_xmlrpc.Client` like in all of the [examples](http://python-wordpress-xmlrpc.readthedocs.org/en/latest/overview.html#quick-start).

**Comment by djiesamsoe** [comment]
sorry, this is my fault.
turns on the server I'm using python with older versions.
